"""Google TV / Android TV Remote v2 client wrapper.

Three states a controller can be in:
- **unpaired**: no cert on disk. Need to discover the TV, run pairing
  (user types PIN that appears on the TV).
- **paired but disconnected**: cert on disk, but the connection isn't live.
  Reconnect happens lazily on next key press (or via keep_reconnecting()).
- **paired + connected**: ready to send keys.

State on disk (under `state_dir`):
- `cert.pem`, `key.pem`: generated by the library during first pair.
- `host.txt`: last-known TV IP. Saved on successful pair.
"""

from __future__ import annotations

import asyncio
import ipaddress
import logging
from pathlib import Path

from androidtvremote2 import AndroidTVRemote

log = logging.getLogger(__name__)

CLIENT_NAME = "Hertford Road"
PAIR_PORT = 6467  # Android TV v2 pairing port
API_PORT = 6466  # Android TV v2 control port


class GTVError(Exception):
    pass


class GoogleTV:
    """Lifecycle-managed wrapper around AndroidTVRemote.

    Designed to live as a singleton on app.state.gtv. Pairing and key-send
    methods are async; connection reconnects lazily on use.
    """

    def __init__(self, state_dir: str | Path) -> None:
        self.state_dir = Path(state_dir)
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.cert_path = self.state_dir / "cert.pem"
        self.key_path = self.state_dir / "key.pem"
        self.host_path = self.state_dir / "host.txt"
        # remote bound to whichever host pairing is happening with right now
        self._pairing: AndroidTVRemote | None = None
        self._remote: AndroidTVRemote | None = None
        self._lock = asyncio.Lock()

    # ------------------------------------------------------------ persistence

    @property
    def paired(self) -> bool:
        return self.cert_path.is_file() and self.key_path.is_file() and self.host_path.is_file()

    @property
    def host(self) -> str | None:
        if not self.host_path.is_file():
            return None
        return self.host_path.read_text().strip() or None

    def _save_host(self, host: str) -> None:
        self.host_path.write_text(host.strip() + "\n")

    def forget(self) -> None:
        """Delete saved cert + host. Forces re-pairing next time."""
        for p in (self.cert_path, self.key_path, self.host_path):
            if p.exists():
                p.unlink()
        self._remote = None

    # ------------------------------------------------------------ pairing

    async def start_pairing(self, host: str) -> None:
        """Open the pairing socket. The TV will show a PIN."""
        if self._pairing is not None:
            try:
                self._pairing.disconnect()
            except Exception:
                pass
        remote = AndroidTVRemote(
            client_name=CLIENT_NAME,
            certfile=str(self.cert_path),
            keyfile=str(self.key_path),
            host=host,
        )
        await remote.async_generate_cert_if_missing()
        try:
            name, mac = await remote.async_get_name_and_mac()
            log.info("starting pair with %s (name=%s mac=%s)", host, name, mac)
        except Exception as e:
            log.warning("get_name_and_mac failed (continuing anyway): %s", e)
        await remote.async_start_pairing()
        self._pairing = remote
        self._pairing_host = host

    async def finish_pairing(self, pin: str) -> None:
        """Submit the PIN. On success, cert is now trusted by the TV."""
        if self._pairing is None:
            raise GTVError("no pairing in progress — call start_pairing first")
        try:
            await self._pairing.async_finish_pairing(pin.strip())
        except Exception as e:
            raise GTVError(f"pairing failed: {e}") from e
        host = self._pairing_host
        self._save_host(host)
        try:
            self._pairing.disconnect()
        except Exception:
            pass
        self._pairing = None
        self._remote = None  # force fresh connect on next use
        log.info("pairing complete with %s", host)

    # ------------------------------------------------------------ connection

    async def _ensure_connected(self) -> AndroidTVRemote:
        if not self.paired:
            raise GTVError("not paired yet — visit /remote to pair")
        if self._remote is None:
            self._remote = AndroidTVRemote(
                client_name=CLIENT_NAME,
                certfile=str(self.cert_path),
                keyfile=str(self.key_path),
                host=self.host,
            )
            try:
                await self._remote.async_connect()
                self._remote.keep_reconnecting()
            except Exception as e:
                self._remote = None
                raise GTVError(f"connect failed: {e}") from e
        return self._remote

    async def send_key(self, key_name: str) -> None:
        """Send a single short-press key. key_name like 'DPAD_UP', 'VOLUME_UP'."""
        async with self._lock:
            remote = await self._ensure_connected()
            try:
                remote.send_key_command(key_name)
            except Exception as e:
                # one reconnect attempt
                log.warning("send_key %s failed (%s) — reconnecting", key_name, e)
                self._remote = None
                remote = await self._ensure_connected()
                remote.send_key_command(key_name)

    async def shutdown(self) -> None:
        for r in (self._remote, self._pairing):
            if r is not None:
                try:
                    r.disconnect()
                except Exception:
                    pass
        self._remote = None
        self._pairing = None


# ============================================================ discovery


async def discover_lan(
    subnet: str = "192.168.8.0/24",
    port: int = API_PORT,
    timeout: float = 0.4,
    concurrency: int = 50,
) -> list[str]:
    """TCP-probe every host in `subnet` for an open `port`.

    Returns hosts that accepted the connection — these are AndroidTV-Remote
    candidates (port 6466 is the v2 API port and is unlikely to be open on
    non-AndroidTV devices on a typical LAN).

    mDNS would be the "correct" way but multicast doesn't cross Docker's
    bridge network by default. TCP probe is a few seconds on a /24 and works
    from inside any container.
    """
    net = ipaddress.ip_network(subnet, strict=False)
    sem = asyncio.Semaphore(concurrency)

    async def probe(ip_str: str) -> str | None:
        async with sem:
            try:
                _, writer = await asyncio.wait_for(
                    asyncio.open_connection(ip_str, port),
                    timeout=timeout,
                )
                writer.close()
                try:
                    await writer.wait_closed()
                except Exception:
                    pass
                return ip_str
            except (asyncio.TimeoutError, OSError):
                return None

    hosts = [str(ip) for ip in net.hosts()]
    results = await asyncio.gather(*[probe(h) for h in hosts])
    return [r for r in results if r]
